<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import LottieCanvas from './LottieCanvas.vue'
import type { LottieAnimation } from './LottiePickerModal.vue'
import type { LottieConfig, LottieInsertAttributes } from '../editor/lottieTypes'

const props = withDefaults(defineProps<{ visible: boolean; animation: LottieAnimation | null; source: string; initial?: Partial<LottieInsertAttributes> | null; title?: string }>(), { initial: null, title: '配置动画' })
const emit = defineEmits<{ 'update:visible': [boolean]; confirm: [LottieConfig]; cancel: [] }>()
const defaults = (): LottieConfig => ({ width: 160, height: 160, autoplay: true, loop: true, speed: 1, fit: 'contain', align: 'center', controls: false, hoverPlay: false, freezeOnOffscreen: true, ariaLabel: '' })
const config = ref<LottieConfig>(defaults())
const configAnimation = computed(() => props.animation)
function syncConfig() { config.value = { ...defaults(), ...(props.animation?.spec.defaults || {}), ...(props.initial || {}) }; if (!config.value.ariaLabel && props.animation) config.value.ariaLabel = props.animation.spec.displayName }
function close() { emit('update:visible', false); emit('cancel') }
function confirm() { if (!props.animation) return; emit('confirm', { ...config.value }); emit('update:visible', false) }
watch(() => props.visible, (visible) => { if (visible) syncConfig() })
watch(() => props.initial, syncConfig, { deep: true })
watch(() => props.animation, syncConfig, { deep: true })
</script>

<template>
  <Teleport to="body"><div v-if="visible" class="config-backdrop" @click.self="close"><section class="config-modal" role="dialog" aria-modal="true" aria-labelledby="lottie-config-title">
    <header class="config-header"><div><p class="eyebrow">Lottie 动画</p><h2 id="lottie-config-title">{{ title }}</h2><p v-if="configAnimation" class="animation-name">{{ configAnimation.spec.displayName }}</p></div><button type="button" class="icon-button" aria-label="关闭" title="关闭" @click="close">×</button></header>
    <div class="config-content"><div class="selected-preview"><LottieCanvas v-if="animation" :src="source" :format="animation.spec.format" :width="config.width" :height="config.height" :autoplay="config.autoplay" :loop="config.loop" :speed="config.speed" :fit="config.fit" :align="config.align" :controls="config.controls" :hover-play="config.hoverPlay" :freeze-on-offscreen="config.freezeOnOffscreen" :aria-label="config.ariaLabel || animation.spec.displayName" /><span v-else class="empty-preview">未选择动画</span></div>
      <fieldset><legend>显示与播放设置</legend><div class="form-grid"><label>宽度（像素）<input v-model.number="config.width" type="number" min="1" max="4096" /></label><label>高度（像素）<input v-model.number="config.height" type="number" min="1" max="4096" /></label><label>播放速度<input v-model.number="config.speed" type="number" min="0.1" max="10" step="0.1" /></label><label>适应方式<select v-model="config.fit"><option value="contain">完整显示</option><option value="cover">覆盖填充</option><option value="fill">拉伸填充</option><option value="fit-width">适应宽度</option><option value="fit-height">适应高度</option></select></label><label>对齐方式<select v-model="config.align"><option value="center">居中</option><option value="top">顶部</option><option value="bottom">底部</option><option value="left">左侧</option><option value="right">右侧</option></select></label></div><div class="toggles"><label><input v-model="config.autoplay" type="checkbox" /> 自动播放</label><label><input v-model="config.loop" type="checkbox" /> 循环播放</label><label><input v-model="config.controls" type="checkbox" /> 显示控制按钮</label><label><input v-model="config.hoverPlay" type="checkbox" /> 悬停时播放</label><label><input v-model="config.freezeOnOffscreen" type="checkbox" /> 离屏时暂停</label></div><label class="aria-field">无障碍标签<input v-model="config.ariaLabel" type="text" :placeholder="animation?.spec.displayName || '动画描述'" /></label></fieldset>
    </div><footer class="config-footer"><button type="button" class="quiet-button" @click="close">取消</button><button type="button" class="primary-button" :disabled="!animation" @click="confirm">确定</button></footer>
  </section></div></Teleport>
</template>

<style scoped>
:global(*) { box-sizing: border-box; }.config-backdrop { position: fixed; inset: 0; z-index: 1100; display: grid; place-items: center; padding: 18px; background: rgb(15 23 42 / 48%); }.config-modal { display: flex; width: min(700px, 100%); max-height: calc(100vh - 36px); flex-direction: column; overflow: hidden; border-radius: 8px; background: #fff; color: #17202a; box-shadow: 0 24px 70px rgb(15 23 42 / 25%); }.config-header,.config-footer { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; padding: 18px 22px; border-bottom: 1px solid #e2e8f0; }.config-header h2 { margin: 0; font-size: 20px; }.animation-name { margin: 5px 0 0; color: #64748b; font-size: 13px; }.eyebrow { margin: 0 0 5px; color: #0f766e; font-size: 11px; font-weight: 700; letter-spacing: .08em; }.icon-button { width: 30px; height: 30px; border: 1px solid #cbd5e1; border-radius: 4px; background: #fff; color: #334155; cursor: pointer; font-size: 20px; }.config-content { display: grid; grid-template-columns: 210px minmax(0, 1fr); gap: 16px; min-height: 0; overflow: auto; padding: 20px 22px; }.selected-preview { display: grid; min-height: 210px; place-items: center; overflow: hidden; border: 1px dashed #cbd5e1; border-radius: 5px; background: #f8fafc; }.empty-preview { color: #94a3b8; font-size: 13px; }fieldset { display: grid; gap: 12px; margin: 0; padding: 12px; border: 1px solid #e2e8f0; border-radius: 5px; }legend { padding: 0 5px; font-size: 12px; font-weight: 700; }.form-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 9px; }.form-grid label,.aria-field { display: grid; gap: 4px; color: #475569; font-size: 12px; }input,select { min-height: 34px; border: 1px solid #cbd5e1; border-radius: 4px; padding: 6px 9px; background: #fff; color: #17202a; font: inherit; }.toggles { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; color: #475569; font-size: 12px; }.toggles input { min-height: auto; accent-color: #0f766e; }.config-footer { justify-content: flex-end; border-top: 1px solid #e2e8f0; border-bottom: 0; }.quiet-button,.primary-button { min-height: 34px; border-radius: 4px; padding: 7px 14px; font: inherit; font-size: 13px; font-weight: 600; cursor: pointer; }.quiet-button { border: 1px solid #cbd5e1; background: #fff; color: #334155; }.primary-button { border: 1px solid #0f766e; background: #0f766e; color: #fff; }button:disabled { cursor: not-allowed; opacity: .5; }@media (max-width: 620px) { .config-content { grid-template-columns: 1fr; }.selected-preview { min-height: 170px; }.form-grid { grid-template-columns: 1fr 1fr; } }
</style>
